components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          description: Nombre del producto.
        price:
          type: number
          description: Precio del producto.
      example:
        name: Producto A
        price: 99.99

  responses:
    res200:
      type: object
      properties:
        message:
          type: string
          description: Mensaje informativo.
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
      example:
        message: Productos obtenidos correctamente.
        products:
          - name: Producto A
            price: 99.99
          - name: Producto B
            price: 49.99

    res201:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de éxito.
      example:
        message: Productos generados correctamente.

    res400:
      type: object
      properties:
        message:
          type: string
          description: Mensaje informativo de error de cliente.
        statusCode:
          type: number
          description: Código de estado HTTP.
      example:
        message: El parámetro 'n' debe ser un número válido.
        statusCode: 400

    res401:
      type: object
      properties:
        message:
          type: string
          description: Falta autenticación para acceder al recurso.
        statusCode:
          type: integer
      example:
        message: No autorizado. Proporcione un token válido.
        statusCode: 401

    res403:
      type: object
      properties:
        message:
          type: string
          description: El usuario no tiene permisos para acceder al recurso.
        statusCode:
          type: integer
      example:
        message: Acceso denegado. No tiene permisos suficientes.
        statusCode: 403

    res404:
      type: object
      properties:
        message:
          type: string
          description: Mensaje informativo de recurso no encontrado.
        statusCode:
          type: number
          description: Código de estado HTTP.
      example:
        message: No se encontraron productos.
        statusCode: 404

    res500:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error del servidor.
        statusCode:
          type: number
          description: Código de estado HTTP.
      example:
        message: Error interno del servidor.
        statusCode: 500

paths:
  /api/products/mocks/{n}:
    get:
      summary: Generar productos.
      description: Genera y guarda `n` productos en la base de datos.
      tags:
        - Products
      parameters:
        - name: n
          in: path
          required: true
          schema:
            type: integer
          description: Número de productos a generar.
      responses:
        "201":
          description: Productos generados correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res201"
        "400":
          description: Parámetro no válido.
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res400"
        "500":
          description: Error al generar productos.
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res500"

  /api/products:
    get:
      summary: Obtener todos los productos.
      description: Retorna todos los productos guardados en la base de datos.
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res200"
        "404":
          description: No se encontraron productos.
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res404"
        "500":
          description: Error al obtener productos.
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res500"
